
### User Registration
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "Rockez666",
  "email": "dfgd251asdf@gmail.com",
  "password": "1234567"
}

### User Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "Rockez666",
  "password": "1234567"
}

> {%
    if (response && response.body) {
        const {accessToken} = response.body;
        client.global.set("accessToken", accessToken);
        console.log("Access token successfully set:", accessToken);

    } else {
        console.error("Response body is undefined or empty.");
    }
%}

### Booking
POST http://localhost:8080/bookings
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "movieId": 3,
  "row": 2,
  "numberSeats": 25
}

### Get bookings
GET http://localhost:8080/users
Authorization: Bearer {{accessToken}}




### ADMIN SERVICE

/



### Create movie
POST http://localhost:8080/admin/movies
Content-Type: application/json
Authorization: Bearer {{accessToken}}


{
  "title": "Fight Club (1999)",
  "description": "An office worker suffering from insomnia meets a mysterious soap salesman named Tyler Durden. Together they form an underground fight club that evolves into something much more.",
  "durationMinutes": 139
}

### Create Screening
POST http://localhost:8080/admin/screenings
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "movieId": 1,
  "startTime": "2025-11-15T14:25:00",
  "hallName": "Main Hall"
}

### Delete Movie
DELETE http://localhost:8080/admin/movies/3
Authorization: Bearer {{accessToken}}


### Delete Screening
DELETE http://localhost:8080/admin/screenings/5
Authorization: Bearer {{accessToken}}



