
### User Registration
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "RanelShma",
  "email": "RanelShma@gmail.com",
  "password": "1234567"
}

### User Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "RanelShma",
  "password": "1234567"
}

> {%
    if (response && response.body) {
        const {accessToken} = response.body;
        client.global.set("accessToken", accessToken);
        console.log("Access token successfully set:", accessToken);

    } else {
        console.error("Response body is undefined or empty.");
    }
%}

### Booking
POST http://localhost:8080/bookings
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "movieId": 2,
  "row": 1,
  "numberSeats": 11
}

### Get bookings
GET http://localhost:8080/users
Authorization: Bearer {{accessToken}}




### ADMIN SERVICE

### Create movie
POST http://localhost:8080/admin/movies
Content-Type: application/json
Authorization: Bearer {{accessToken}}


{
  "title": "The Dark Knight (2008)",
  "description": "Batman faces Joker chaos.",
  "durationMinutes": 152
}

### Create Screening
POST http://localhost:8080/admin/screenings
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "movieId": 6,
  "startTime": "2025-11-20T20:31:00",
  "hallName": "IMAX"
}

### Delete Movie
DELETE http://localhost:8080/admin/movies/5
Authorization: Bearer {{accessToken}}


### Delete Screening
DELETE http://localhost:8080/admin/screenings/2
Authorization: Bearer {{accessToken}}



